apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip-rule-operator
  name: ip-rule-operator-agent-editor-role
rules:
- apiGroups:
  - api.operator.brtrm.dev
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.operator.brtrm.dev
  resources:
  - agents/status
  verbs:
  - get
