apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "api.operator.brtrm.dev/v1alpha1",
          "kind": "Agent",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ip-rule-operator"
            },
            "name": "agent-sample"
          },
          "spec": {
            "nodeselector": {
              "kubernetes.io/os": "linux"
            }
          }
        },
        {
          "apiVersion": "api.operator.brtrm.dev/v1alpha1",
          "kind": "IPRule",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ip-rule-operator"
            },
            "name": "iprule-sample"
          },
          "spec": {
            "cidr": "10.0.0.0/24",
            "table": 254
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-10-31T22:01:20Z"
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: ip-rule-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Agent
        name: agents.api.operator.brtrm.dev
        version: v1alpha1
      - kind: IPRuleConfig
        name: ipruleconfigs.api.operator.brtrm.dev
        version: v1alpha1
      - kind: IPRule
        name: iprules.api.operator.brtrm.dev
        version: v1alpha1
  description: Manages Ip Rules for VRF BGP LB IPs
  displayName: ip-rule-operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: ip-rule-operator
            control-plane: controller-manager
          name: controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: ip-rule-operator
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: ip-rule-operator
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --metrics-bind-address=:8443
                      - --leader-elect
                      - --health-probe-bind-address=:8081
                    command:
                      - /manager
                    image: ghcr.io/mariusbertram/iprule-controller@sha256:3b86a4a96a421aa75e46d0c9e6988dfba4cf1cf304309f65ec1637239cd104f2
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: controller-manager
                terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - Network
  links:
    - name: Ip Rule Operator
      url: https://ip-rule-operator.domain
  maintainers:
    - email: marius@brtrm.de
      name: Marius Bertram
  maturity: alpha
  provider:
    name: Marius Bertram
    url: github.com/mariusbertram/ip-rule-operator
  relatedImages:
    - image: ghcr.io/mariusbertram/iprule-controller@sha256:3b86a4a96a421aa75e46d0c9e6988dfba4cf1cf304309f65ec1637239cd104f2
      name: manager
    - image: ghcr.io/mariusbertram/iprule-agent@sha256:f6ca1f929a44cd69ba5f4980bf8ec1b119275540b6a8d3f706c657b1eca0eab6
      name: agent
  version: 0.0.1
