apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip-rule-operator
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ip-rule-leader-election-role
subjects:
- kind: ServiceAccount
  name: ip-rule-controller-manager
  namespace: ip-rule-operator
