apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: iprule-agent-scc
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - ip-rule-operator-iprule-agent-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use