apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ip-rule-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Manages Ip Rules for VRF BGP LB IPs
  displayName: ip-rule-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Network
  links:
  - name: Ip Rule Operator
    url: https://ip-rule-operator.domain
  maintainers:
  - email: marius@brtrm.de
    name: Marius Bertram
  maturity: alpha
  provider:
    name: Marius Bertram
    url: github.com/mariusbertram/ip-rule-operator
  version: 0.0.0
