apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iprule-agent
  namespace: system
  labels:
    app.kubernetes.io/name: ip-rule-operator
spec:
  selector:
    matchLabels:
      app: iprule-agent
  template:
    metadata:
      labels:
        app: iprule-agent
    spec:
      serviceAccountName: iprule-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      # Optional: auch auf Master/Control-Plane Nodes laufen lassen
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      # - key: node-role.kubernetes.io/control-plane
      #   operator: Exists
      #   effect: NoSchedule
      nodeSelector:
        iprule.operator.brtrm.dev/enabled: "true"
      containers:
      - name: agent
        image: iprule-agent:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_ADMIN"]
          runAsNonRoot: false
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: RECONCILE_PERIOD
          value: 10s
        - name: METRICS_ADDR
          value: ":9090"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3
